
export const INGREDIENT_NAME_MAP = {
  Banana: "Banana",
  Basil: "Basil",
  BrChick: "Chicken breast",
  Butter: "Butter",
  CGarlic: "Garlic",
  Carrot: "Carrot",
  Carrot_Sliced: "Sliced carrot",
  Cheeze: "Cheese",
  Cocoa: "Cocoa",
  ComChic: "Chicken thigh",
  ComEgg: "Egg",
  ComEggPlant: "Eggplant",
  ComFish: "Fish",
  ComFish_Nohead: "Fish",
  Egg: "Egg",
  EggPlant: "Eggplant",
  Eggplant_Sliced: "Eggplant",
  Fish_Or_Circ: "Fish (round cut)",
  Fish_Or_Fille: "Fish fillet (round cut)",
  Fish_Wi_Circ: "Fish (round cut)",
  Fish_Wi_Fille: "Fish fillet",
  Flour: "Flour",
  GBellP: "Green bell pepper",
  GBellP_Sliced: "Sliced green bell pepper",
  Garlic: "Garlic",
  GrMeat: "Ground meat",
  HOnion: "Yellow onion",
  HPotato: "Potato",
  HTomato: "Tomato",
  Lasagna: "Lasagna sheets",
  LegChic: "Chicken drumstick",
  Legum: "Legumes",
  Lime: "Lemon",
  LimeComG: "Lime",
  LimeComY: "Lemon",
  Milk: "Milk",
  Mushroom: "Mushroom",
  Mushroom_Sliced: "Sliced mushroom",
  NGrMeat: "Beef",
  Nut: "Nuts",
  Nuts: "Nuts",
  Onion_Garlic: "Onion & garlic",
  OrOnion: "Onion",
  Parsely: "Parsley",
  Pasta: "Pasta",
  PepperG: "Green pepper",
  PepperR: "Red pepper",
  Potato: "Potato",
  Potato_NoSkin: "Peeled potato",
  PurOnion: "Purple onion",
  RBellP: "Red bell pepper",
  RBellP_Sliced: "Sliced red bell pepper",
  Rice: "Rice",
  Saus: "Sausage",
  ShrimGroup: "Shrimp",
  Shrimp: "Shrimp",
  Spagetti: "Spaghetti",
  Steak: "Steak",
  Sugar: "Sugar",
  ThiChic: "Thai chicken",
  Tomato: "Tomato",
  Walnut: "Walnut",
  WhOnion: "White onion",
  WinChic: "Chicken wings",
  YBellP: "Yellow bell pepper",
  YBellP_Sliced: "Sliced yellow bell pepper",
  Yogurt: "Yogurt",
  Zucchini: "Zucchini",
  Zucchini_Sliced: "Sliced zucchini",
};
